osx_image: xcode7.1
language: objective-c
podfile: Demo/Podfile
cache: cocoapods

script: cd Demo ; set -o pipefail && xcodebuild -workspace 'Demo.xcworkspace' -scheme 'Demo' -configuration 'Debug' -sdk iphonesimulator -destination platform='iOS Simulator',OS='9.1',name='iPhone 6s' build test  | xcpretty -c --test
